// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/niedervolt/DesktopTable.tsx": () => import("../components/mockups/niedervolt/DesktopTable.tsx"),
  "./components/mockups/niedervolt/MobileCard.tsx": () => import("../components/mockups/niedervolt/MobileCard.tsx")
};
